config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "articles#index"
  resources :articles
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
#   get "/articles", to: "articles#index"
#   get "/articles/:id", to: "articles#show"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(title: "...", body: "...")
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Hello, Rails!!!</h1>
<h1>List of Articles</h1>
<p>Articles:</p>
    <ul>
        <% @articles.each do |article| %>
        <li>
            <%= link_to article.title, article%>
            <!--
            <a href="<%= article_path(article) %>">
             <%= article.title%>
            </a>
            -->                          
        </li>
        
        <% end %>
    </ul>
                                              

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form|%>

<div>
    
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p> <%= @article.body %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>